# Generated by Django 5.2.6 on 2025-09-30 21:20

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_usercourse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('not_apply', 'Not Applied'), ('applied', 'Applied'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='about',
            field=models.TextField(blank=True, null=True, validators=[Users.models.validate_about_length]),
        ),
    ]
