# Generated by Django 5.2.6 on 2025-10-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_usercourse_status_alter_userdata_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('not_applied', 'Not Applied'), ('applied', 'Applied'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='applied', max_length=20),
        ),
    ]
