# Generated by Django 5.2.6 on 2025-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_usercourse_modified_at_alter_usercourse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('not_applied', 'Not Applied'), ('applied', 'Applied'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_applied', max_length=20),
        ),
    ]
