# Generated by Django 5.2.6 on 2025-10-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_usercourse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
