# Generated by Django 5.2.6 on 2025-10-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='portfolio_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
